// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSMgpofOcrVzWS9JgBlBsincGOAcv7XXE',
    appId: '1:266329530255:web:b2d991333377b1737ef5fa',
    messagingSenderId: '266329530255',
    projectId: 'the-reminder-app-7e0e4',
    authDomain: 'the-reminder-app-7e0e4.firebaseapp.com',
    storageBucket: 'the-reminder-app-7e0e4.firebasestorage.app',
    measurementId: 'G-MS3VZ30QNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxsm8N2csSEiMLgMaeCmA8ay6CS1BRvWs',
    appId: '1:266329530255:android:5909a51f5432ff177ef5fa',
    messagingSenderId: '266329530255',
    projectId: 'the-reminder-app-7e0e4',
    storageBucket: 'the-reminder-app-7e0e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmqttUvZgukVoxHfqdndHjLcg955ZI_20',
    appId: '1:266329530255:ios:7fc10f830ceab0a57ef5fa',
    messagingSenderId: '266329530255',
    projectId: 'the-reminder-app-7e0e4',
    storageBucket: 'the-reminder-app-7e0e4.firebasestorage.app',
    iosBundleId: 'com.example.theReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmqttUvZgukVoxHfqdndHjLcg955ZI_20',
    appId: '1:266329530255:ios:7fc10f830ceab0a57ef5fa',
    messagingSenderId: '266329530255',
    projectId: 'the-reminder-app-7e0e4',
    storageBucket: 'the-reminder-app-7e0e4.firebasestorage.app',
    iosBundleId: 'com.example.theReminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSMgpofOcrVzWS9JgBlBsincGOAcv7XXE',
    appId: '1:266329530255:web:7c09d8cdfa09189d7ef5fa',
    messagingSenderId: '266329530255',
    projectId: 'the-reminder-app-7e0e4',
    authDomain: 'the-reminder-app-7e0e4.firebaseapp.com',
    storageBucket: 'the-reminder-app-7e0e4.firebasestorage.app',
    measurementId: 'G-2MZ7XQKJ2D',
  );
}
