// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:the_reminder_app/models/planner_models.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AlarmEntryAdapter());
    registerAdapter(AppUserAdapter());
    registerAdapter(HydrationLogAdapter());
    registerAdapter(ReminderAdapter());
    registerAdapter(ReminderPriorityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AlarmEntryAdapter());
    registerAdapter(AppUserAdapter());
    registerAdapter(HydrationLogAdapter());
    registerAdapter(ReminderAdapter());
    registerAdapter(ReminderPriorityAdapter());
  }
}
